# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/VIVADO/jizu/cpuyep/cpuyep.cache/wt [current_project]
set_property parent.project_path E:/VIVADO/jizu/cpuyep/cpuyep.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo e:/VIVADO/jizu/cpuyep/cpuyep.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/VIVADO/jizu/cpuyep/testcoe.coe
add_files E:/VIVADO/jizu/cpuyep/ROM.coe
add_files E:/VIVADO/jizu/cpuyep/ROM_without_BR.coe
add_files E:/VIVADO/jizu/cpuyep/ROM_with_Address_version.coe
add_files E:/VIVADO/jizu/cpuyep/test_add.coe
add_files E:/VIVADO/jizu/cpuyep/test_1to100.coe
add_files E:/VIVADO/jizu/cpuyep/ROM_full_version.coe
add_files E:/VIVADO/jizu/cpuyep/ROM_full_version_to_latest.coe
add_files E:/VIVADO/jizu/cpuyep/test_add_16.coe
add_files E:/VIVADO/jizu/cpuyep/test_sub_16.coe
add_files E:/VIVADO/jizu/cpuyep/test_sub_16_JMPGEZ.coe
add_files E:/VIVADO/jizu/cpuyep/instuction.coe
add_files E:/VIVADO/jizu/cpuyep/ins.coe
read_verilog -library xil_defaultlib {
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/ACC.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/ALU.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/BR.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/CU.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/DISPLAY.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/IR.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/MAR.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/MBR.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/PC.v
  E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/new/top.v
}
read_ip -quiet E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all e:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet E:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/VIVADO/jizu/cpuyep/cpuyep.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/VIVADO/jizu/cpuyep/cpuyep.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files E:/VIVADO/jizu/cpuyep/cpuyep.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
